[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']
[[plugins]]
repo      = 'Shougo/unite-help'
on_source = ['unite.vim']
[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = ['unite.vim']
[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']
[[plugins]]
repo = 'sgur/unite-qf'
on_source = ['unite.vim']
[[plugins]]
repo = 'kmnk/vim-unite-svn'
on_source = ['unite.vim']
[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = ['unite.vim']


[[plugins]]
repo   = 'Shougo/vimfiler.vim'
[[plugins]]
repo   = 'Shougo/vimshell.vim'
[[plugins]]
repo   = 'Shougo/tabpagebuffer.vim'


[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'thinca/vim-qfreplace'
[[plugins]]
repo = 'thinca/vim-singleton'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'motemen/git-vim'
[[plugins]]
repo = 't9md/vim-textmanip'
[[plugins]]
repo = 'h1mesuke/ref-dicts-en'
[[plugins]]
repo = 'mattn/gist-vim'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'fuenor/qfixhowm'
[[plugins]]
repo = 'kana/vim-fakeclip'
[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'mattn/vdbi-vim'
[[plugins]]
repo = 'mattn/qiita-vim'
[[plugins]]
repo = 'vim-scripts/grep.vim'
[[plugins]]
repo = 'vim-scripts/copypath.vim'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'vim-scripts/The-NERD-Commenter'
[[plugins]]
repo = 'rking/ag.vim'
[[plugins]]
repo = 'tpope/vim-cucumber.git'
[[plugins]]
repo = 'tpope/vim-dispatch.git'
[[plugins]]
repo = 'hrsh7th/vim-versions.git'

[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'mileszs/ack.vim'
[[plugins]]
repo = 'terryma/vim-multiple-cursors'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'
